name: Schedule Probe

on:
  workflow_dispatch:
  schedule:
    - cron: "19,49 * * * *"

jobs:
  probe:
    runs-on: ubuntu-latest

    steps:
      - name: Print schedule probe timestamp
        run: date -u

